In [23]:
import joblib
import pandas as pd

In [3]:
# load model 1X2
model_results = \
"../data/euro20_results.joblib"
loaded_model = \
joblib.load(model_results)

# load model goals
model_goals = \
"../data/euro20_goals.joblib"
loaded_model_goals = \
joblib.load(model_goals)

# load data
# matches Group Euro 2024
github = 'https://raw.githubusercontent.com/martj42' 
df_allmatches = pd.read_csv(
f'{github}/international_results/master/results.csv')

# matches Qualifiers Euro 2024
df_qual_24 = pd.read_csv(
    '../data/euro24_qualifiers_norm.csv',
    index_col=0)

In [6]:
df_group_24 = df_allmatches[
  (df_allmatches.tournament=='UEFA Euro') & 
  (df_allmatches.date>='2024-06-14') & 
  (df_allmatches.date<='2024-06-26')]
len(df_group_24)

36

In [7]:
group_24_teams = \
list(df_group_24.home_team.unique()) + \
list(df_group_24.away_team.unique())
# eliminate duplicates 
group_24_teams = list(set(group_24_teams))

In [9]:
df_qual_24_filter = df_qual_24[
    df_qual_24.team_name.isin(group_24_teams)]

qual_24_teams = \
df_qual_24_filter['team_name'].unique()
len(qual_24_teams)

21

In [10]:
group_24_teams.extend(['Czechia', 'Türkiye'])
df_qual_24_filter = df_qual_24[
    (df_qual_24.team_name.isin(group_24_teams))]
df_qual_24_filter

,team_name,goals,attempts,attempts_on_target,attempts_off_target,attempts_blocked,matches_appearance,passes_accuracy,passes_attempted,passes_completed,...,clearance_attempted,saves,goals_conceded,own_goal_conceded,saves_on_penalty,clean_sheet,fouls_committed,fouls_suffered,yellow_cards,red_cards
0,Portugal,3.600,19.300,8.100,6.900,4.300,1.0,89.60,683.400,613.600,...,10.100,1.600,0.200,0.000,0.000,0.900,9.200,9.800,1.100,0.000
1,France,3.625,20.750,7.875,7.500,5.375,1.0,90.00,667.625,603.000,...,10.625,1.875,0.375,0.000,0.125,0.750,9.875,9.500,1.500,0.000
2,Spain,3.125,17.750,6.750,7.000,4.000,1.0,90.75,726.875,660.000,...,9.250,1.375,0.625,0.000,0.000,0.500,9.750,9.375,2.000,0.000
3,Switzerland,2.200,16.300,5.900,7.300,3.100,1.0,89.40,670.900,600.500,...,11.000,1.400,1.100,0.000,0.000,0.300,9.200,8.600,1.900,0.100
5,Belgium,2.750,14.875,5.250,5.375,4.250,1.0,86.00,495.250,427.750,...,14.125,2.000,0.500,0.125,0.000,0.625,8.625,9.750,1.625,0.125
6,England,2.750,12.500,5.750,3.625,3.125,1.0,89.75,638.250,575.375,...,9.500,0.625,0.500,0.000,0.125,0.500,9.250,11.625,1.750,0.125
7,Slovenia,2.000,12.500,4.200,4.900,3.400,1.0,81.30,505.700,418.700,...,18.600,2.300,0.900,0.000,0.000,0.400,11.300,11.300,1.000,0.000
8,Denmark,1.900,15.600,5.400,6.400,3.800,1.0,87.10,688.900,601.900,...,10.200,1.100,1.000,0.000,0.000,0.300,8.500,10.700,1.400,0.000
11,Netherlands,2.125,17.750,6.375,6.250,5.125,1.0,88.13,589.000,521.875,...,12.375,1.750,0.875,0.000,0.000,0.625,12.250,9.625,1.500,0.000
12,Austria,2.125,16.625,6.625,6.625,3.375,1.0,81.75,454.125,374.250,...,16.000,1.875,0.875,0.000,0.000,0.375,10.000,10.750,1.875,0.125
13,Slovakia,1.700,13.300,3.800,5.200,4.300,1.0,83.50,485.400,406.400,...,16.500,3.100,0.800,0.100,0.000,0.500,11.700,12.900,1.800,0.000
14,Scotland,2.125,10.125,3.250,4.000,2.875,1.0,81.75,440.250,371.375,...,14.000,2.375,1.000,0.000,0.000,0.500,12.625,13.125,2.375,0.000
15,Romania,1.600,14.500,4.800,5.800,3.900,1.0,77.80,438.900,352.700,...,18.300,3.000,0.500,0.000,0.000,0.600,10.700,10.400,2.300,0.100
16,Italy,2.000,15.750,4.500,6.625,4.625,1.0,87.50,608.125,533.375,...,7.000,1.875,1.125,0.000,0.000,0.375,11.500,10.875,1.750,0.000
17,Hungary,2.000,15.375,5.500,5.625,4.250,1.0,82.75,532.125,443.875,...,18.500,2.750,0.875,0.125,0.000,0.375,12.250,12.125,2.500,0.250
19,Poland,1.500,16.000,4.700,6.200,5.100,1.0,84.30,593.300,502.300,...,16.200,1.500,1.100,0.000,0.000,0.400,12.000,12.800,2.000,0.000
20,Serbia,1.875,13.875,4.500,6.125,3.250,1.0,86.63,582.625,504.500,...,14.125,1.625,1.125,0.000,0.000,0.250,11.625,12.250,1.500,0.000
21,Ukraine,1.500,10.700,4.100,4.300,2.300,1.0,83.60,451.900,379.000,...,17.900,3.100,1.000,0.100,0.000,0.300,13.600,9.300,2.200,0.000
23,Türki̇ye,1.750,15.500,5.625,6.750,3.125,1.0,85.38,534.500,458.500,...,17.875,3.125,0.875,0.125,0.000,0.375,11.250,11.375,3.375,0.000
25,Georgia,1.400,11.200,3.100,4.800,3.300,1.0,82.40,426.400,354.900,...,18.700,3.400,1.800,0.200,0.000,0.300,11.100,9.900,2.700,0.100
27,Croatia,1.625,18.250,7.375,6.625,4.250,1.0,88.75,688.750,613.375,...,12.750,2.375,0.500,0.000,0.000,0.625,8.250,8.625,1.375,0.000
30,Czechia,1.500,16.750,5.125,7.375,4.250,1.0,78.88,485.625,388.375,...,15.875,1.625,0.750,0.000,0.000,0.500,12.250,11.500,1.875,0.125
31,Albania,1.500,9.000,3.750,4.125,1.125,1.0,82.00,472.000,393.250,...,25.000,2.625,0.500,0.000,0.000,0.500,10.750,14.625,2.000,0.000

In [13]:
sel_feats = ['goals', 'attempts', 'attempts_on_target', 'attempts_off_target',
             'passes_accuracy', 'passes_attempted',
             'ball_possession', 'cross_accuracy', 'cross_attempted', 
             'free_kick', 'attacks', 'assists', 'corners',
             'offsides', 'recovered_ball', 'tackles', 
             'clearance_attempted', 'saves',
             'goals_conceded', 'fouls_committed', 'fouls_suffered']


df_qual_24_filter[['team_name']+sel_feats]

,team_name,goals,attempts,attempts_on_target,attempts_off_target,passes_accuracy,passes_attempted,ball_possession,cross_accuracy,cross_attempted,...,assists,corners,offsides,recovered_ball,tackles,clearance_attempted,saves,goals_conceded,fouls_committed,fouls_suffered
0,Portugal,3.600,19.300,8.100,6.900,89.60,683.400,63.30,28.17,24.500,...,2.800,7.200,2.500,42.200,8.500,10.100,1.600,0.200,9.200,9.800
1,France,3.625,20.750,7.875,7.500,90.00,667.625,60.13,31.15,22.875,...,2.125,5.625,1.875,37.125,12.375,10.625,1.875,0.375,9.875,9.500
2,Spain,3.125,17.750,6.750,7.000,90.75,726.875,67.63,28.58,26.250,...,2.750,6.875,2.250,34.500,8.625,9.250,1.375,0.625,9.750,9.375
3,Switzerland,2.200,16.300,5.900,7.300,89.40,670.900,66.41,24.61,25.600,...,1.600,5.900,2.600,35.900,7.500,11.000,1.400,1.100,9.200,8.600
5,Belgium,2.750,14.875,5.250,5.375,86.00,495.250,58.13,26.54,18.375,...,2.500,7.625,1.375,32.250,8.125,14.125,2.000,0.500,8.625,9.750
6,England,2.750,12.500,5.750,3.625,89.75,638.250,62.63,34.17,15.000,...,1.625,4.500,0.875,34.125,8.625,9.500,0.625,0.500,9.250,11.625
7,Slovenia,2.000,12.500,4.200,4.900,81.30,505.700,53.90,28.58,14.000,...,1.400,3.800,2.100,35.700,9.300,18.600,2.300,0.900,11.300,11.300
8,Denmark,1.900,15.600,5.400,6.400,87.10,688.900,64.20,27.72,26.700,...,1.600,8.200,0.900,37.300,8.200,10.200,1.100,1.000,8.500,10.700
11,Netherlands,2.125,17.750,6.375,6.250,88.13,589.000,57.38,26.81,24.250,...,1.750,7.250,1.250,37.375,10.875,12.375,1.750,0.875,12.250,9.625
12,Austria,2.125,16.625,6.625,6.625,81.75,454.125,55.13,26.67,18.750,...,1.250,5.250,2.000,39.125,12.375,16.000,1.875,0.875,10.000,10.750
13,Slovakia,1.700,13.300,3.800,5.200,83.50,485.400,52.70,26.59,17.300,...,1.300,7.300,2.700,38.300,12.200,16.500,3.100,0.800,11.700,12.900
14,Scotland,2.125,10.125,3.250,4.000,81.75,440.250,46.88,25.18,17.375,...,1.500,4.375,0.875,33.750,8.750,14.000,2.375,1.000,12.625,13.125
15,Romania,1.600,14.500,4.800,5.800,77.80,438.900,52.00,19.88,16.100,...,0.900,5.000,1.600,36.800,11.300,18.300,3.000,0.500,10.700,10.400
16,Italy,2.000,15.750,4.500,6.625,87.50,608.125,58.88,26.76,19.625,...,1.750,6.750,1.750,40.125,11.625,7.000,1.875,1.125,11.500,10.875
17,Hungary,2.000,15.375,5.500,5.625,82.75,532.125,55.75,30.44,20.125,...,1.500,5.125,1.750,39.375,11.375,18.500,2.750,0.875,12.250,12.125
19,Poland,1.500,16.000,4.700,6.200,84.30,593.300,61.80,26.50,26.800,...,1.300,6.800,1.200,34.500,9.700,16.200,1.500,1.100,12.000,12.800
20,Serbia,1.875,13.875,4.500,6.125,86.63,582.625,59.50,29.85,23.875,...,1.750,5.875,1.625,36.500,10.000,14.125,1.625,1.125,11.625,12.250
21,Ukraine,1.500,10.700,4.100,4.300,83.60,451.900,50.50,23.02,12.600,...,1.000,4.200,1.500,34.700,9.400,17.900,3.100,1.000,13.600,9.300
23,Türki̇ye,1.750,15.500,5.625,6.750,85.38,534.500,58.13,25.00,22.500,...,1.500,5.375,1.625,40.250,11.375,17.875,3.125,0.875,11.250,11.375
25,Georgia,1.400,11.200,3.100,4.800,82.40,426.400,43.40,23.72,9.700,...,0.900,2.100,1.000,38.200,15.100,18.700,3.400,1.800,11.100,9.900
27,Croatia,1.625,18.250,7.375,6.625,88.75,688.750,62.50,27.98,21.000,...,1.250,5.875,1.625,39.875,8.500,12.750,2.375,0.500,8.250,8.625
30,Czechia,1.500,16.750,5.125,7.375,78.88,485.625,53.88,26.73,27.125,...,1.000,5.125,2.250,38.750,11.375,15.875,1.625,0.750,12.250,11.500
31,Albania,1.500,9.000,3.750,4.125,82.00,472.000,52.00,26.16,8.125,...,1.000,2.625,2.000,36.250,7.500,25.000,2.625,0.500,10.750,14.625

In [14]:
df_group_24.replace('Czech Republic', 'Czechia', inplace=True)
df_group_24.replace('Turkey', 'Türkiye', inplace=True)
df_group_24 = df_group_24[df_group_24['home_team'] != 'Germany']
df_group_24

/Users/tropianhs/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4263: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
47076,2024-06-15,Hungary,Switzerland,NaN,NaN,UEFA Euro,Cologne,Germany,True
47077,2024-06-15,Spain,Croatia,NaN,NaN,UEFA Euro,Berlin,Germany,True
47078,2024-06-15,Italy,Albania,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47079,2024-06-16,Slovenia,Denmark,NaN,NaN,UEFA Euro,Stuttgart,Germany,True
47080,2024-06-16,Serbia,England,NaN,NaN,UEFA Euro,Gelsenkirchen,Germany,True
47081,2024-06-16,Poland,Netherlands,NaN,NaN,UEFA Euro,Hamburg,Germany,True
47082,2024-06-17,Austria,France,NaN,NaN,UEFA Euro,Düsseldorf,Germany,True
47083,2024-06-17,Romania,Ukraine,NaN,NaN,UEFA Euro,Munich,Germany,True
47084,2024-06-17,Belgium,Slovakia,NaN,NaN,UEFA Euro,Frankfurt,Germany,True
47085,2024-06-18,Türki̇ye,Georgia,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47086,2024-06-18,Portugal,Czechia,NaN,NaN,UEFA Euro,Leipzig,Germany,True
47088,2024-06-19,Scotland,Switzerland,NaN,NaN,UEFA Euro,Cologne,Germany,True
47089,2024-06-19,Croatia,Albania,NaN,NaN,UEFA Euro,Hamburg,Germany,True
47090,2024-06-20,Spain,Italy,NaN,NaN,UEFA Euro,Gelsenkirchen,Germany,True
47091,2024-06-20,Slovenia,Serbia,NaN,NaN,UEFA Euro,Munich,Germany,True
47092,2024-06-20,Denmark,England,NaN,NaN,UEFA Euro,Frankfurt,Germany,True
47093,2024-06-21,Poland,Austria,NaN,NaN,UEFA Euro,Berlin,Germany,True
47094,2024-06-21,Netherlands,France,NaN,NaN,UEFA Euro,Leipzig,Germany,True
47095,2024-06-21,Slovakia,Ukraine,NaN,NaN,UEFA Euro,Düsseldorf,Germany,True
47096,2024-06-22,Belgium,Romania,NaN,NaN,UEFA Euro,Cologne,Germany,True
47097,2024-06-22,Georgia,Czechia,NaN,NaN,UEFA Euro,Hamburg,Germany,True
47098,2024-06-22,Türki̇ye,Portugal,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47100,2024-06-23,Scotland,Hungary,NaN,NaN,UEFA Euro,Stuttgart,Germany,True
47101,2024-06-24,Albania,Spain,NaN,NaN,UEFA Euro,Düsseldorf,Germany,True
47102,2024-06-24,Croatia,Italy,NaN,NaN,UEFA Euro,Leipzig,Germany,True
47103,2024-06-25,England,Slovenia,NaN,NaN,UEFA Euro,Cologne,Germany,True
47104,2024-06-25,Denmark,Serbia,NaN,NaN,UEFA Euro,Munich,Germany,True
47105,2024-06-25,Netherlands,Austria,NaN,NaN,UEFA Euro,Berlin,Germany,True
47106,2024-06-25,France,Poland,NaN,NaN,UEFA Euro,Dortmund,Germany,True
47107,2024-06-26,Slovakia,Romania,NaN,NaN,UEFA Euro,Frankfurt,Germany,True
47108,2024-06-26,Ukraine,Belgium,NaN,NaN,UEFA Euro,Stuttgart,Germany,True
47109,2024-06-26,Georgia,Portugal,NaN,NaN,UEFA Euro,Gelsenkirchen,Germany,True
47110,2024-06-26,Czechia,Türki̇ye,NaN,NaN,UEFA Euro,Hamburg,Germany,True

In [15]:
# create dataset 
# home, away, stats_home, stats_away, result (H, D, A)

all_stats = []

# loop on the df_group_24
for idx, row in df_group_24.iterrows():
    
    match_stats = []
    home_team = row['home_team']
    away_team = row['away_team']
    
    home_stats = df_qual_24_filter[df_qual_24_filter['team_name']==home_team].copy()
    away_stats = df_qual_24_filter[df_qual_24_filter['team_name']==away_team].copy()
        
    home_stats = home_stats.add_suffix('_home')
    away_stats = away_stats.add_suffix('_away')
    
    
    match_stats.extend(home_stats.values[0])
    match_stats.extend(away_stats.values[0])
    
    all_stats.append(match_stats)

print(all_stats[0])

['Hungary', 2.0, 15.375, 5.5, 5.625, 4.25, 1.0, 82.75, 532.125, 443.875, 55.75, 30.44, 20.125, 6.125, 14.375, 38.375, 1.5, 5.125, 1.75, 39.375, 11.375, 18.5, 2.75, 0.875, 0.125, 0.0, 0.375, 12.25, 12.125, 2.5, 0.25, 'Switzerland', 2.2, 16.3, 5.9, 7.3, 3.1, 1.0, 89.4, 670.9, 600.5, 66.41, 24.61, 25.6, 6.3, 10.4, 49.5, 1.6, 5.9, 2.6, 35.9, 7.5, 11.0, 1.4, 1.1, 0.0, 0.0, 0.3, 9.2, 8.6, 1.9, 0.1]

In [27]:
columns = list(home_stats.columns) + list(away_stats.columns) 
df_matches_stats = pd.DataFrame(all_stats, columns=columns)
df_matches_stats.head()

,team_name_home,goals_home,attempts_home,attempts_on_target_home,attempts_off_target_home,attempts_blocked_home,matches_appearance_home,passes_accuracy_home,passes_attempted_home,passes_completed_home,...,clearance_attempted_away,saves_away,goals_conceded_away,own_goal_conceded_away,saves_on_penalty_away,clean_sheet_away,fouls_committed_away,fouls_suffered_away,yellow_cards_away,red_cards_away
0,Hungary,2.000,15.375,5.50,5.625,4.250,1.0,82.75,532.125,443.875,...,11.00,1.400,1.1,0.0,0.000,0.300,9.20,8.600,1.900,0.100
1,Spain,3.125,17.750,6.75,7.000,4.000,1.0,90.75,726.875,660.000,...,12.75,2.375,0.5,0.0,0.000,0.625,8.25,8.625,1.375,0.000
2,Italy,2.000,15.750,4.50,6.625,4.625,1.0,87.50,608.125,533.375,...,25.00,2.625,0.5,0.0,0.000,0.500,10.75,14.625,2.000,0.000
3,Slovenia,2.000,12.500,4.20,4.900,3.400,1.0,81.30,505.700,418.700,...,10.20,1.100,1.0,0.0,0.000,0.300,8.50,10.700,1.400,0.000
4,Serbia,1.875,13.875,4.50,6.125,3.250,1.0,86.63,582.625,504.500,...,9.50,0.625,0.5,0.0,0.125,0.500,9.25,11.625,1.750,0.125

In [28]:
X = df_matches_stats.drop(labels=['team_name_home', 'team_name_away'],
             axis=1)

Y = loaded_model.predict(X)

# decode predictions
predictions = ['X' if pred==0 else str(pred) for pred in Y]

# add back to the matches 
df_matches_stats['result_prediction'] = predictions
# check the slip
df_matches_stats[['team_name_home', 'team_name_away', 'result_prediction']]

   team_name_home team_name_away result_prediction
0         Hungary    Switzerland                 1
1           Spain        Croatia                 X
2           Italy        Albania                 1
3        Slovenia        Denmark                 1
4          Serbia        England                 1
5          Poland    Netherlands                 2
6         Austria         France                 1
7         Romania        Ukraine                 2
8         Belgium       Slovakia                 X
9        Türki̇ye        Georgia                 X
10       Portugal        Czechia                 1
11       Scotland    Switzerland                 2
12        Croatia        Albania                 X
13          Spain          Italy                 1
14       Slovenia         Serbia                 1
15        Denmark        England                 1
16         Poland        Austria                 2
17    Netherlands         France                 2
18       Slovakia        Ukraine                 2
19        Belgium        Romania                 X
20        Georgia        Czechia                 X
21       Türki̇ye       Portugal                 2
22       Scotland        Hungary                 2
23        Albania          Spain                 2
24        Croatia          Italy                 X
25        England       Slovenia                 X
26        Denmark         Serbia                 X
27    Netherlands        Austria                 X
28         France         Poland                 X
29       Slovakia        Romania                 X
30        Ukraine        Belgium                 2
31        Georgia       Portugal                 2
32        Czechia       Türki̇ye                 2

In [29]:
# extract probabilities
Y_proba = loaded_model.predict_proba(X)
max_prob = [max(prob) for prob in Y_proba]

df_matches_stats['prob'] = max_prob
df_matches_stats[df_matches_stats.prob>=0.6][
    ['team_name_home', 'team_name_away', 
     'result_prediction', 'prob']]

   team_name_home team_name_away result_prediction  prob
10       Portugal        Czechia                 1   0.6
12        Croatia        Albania                 X   0.6
13          Spain          Italy                 1   0.6
19        Belgium        Romania                 X   0.8
21       Türki̇ye       Portugal                 2   0.6
25        England       Slovenia                 X   0.7
30        Ukraine        Belgium                 2   0.6

In [30]:
X = df_matches_stats.drop(labels=['team_name_home', 
                                  'team_name_away', 
                                  'result_prediction',
                                  'prob'],
             axis=1)

Y = loaded_model_goals.predict(X)

# add back to the matches 
df_matches_stats['goals_prediction'] = Y
# check the slip
df_matches_stats[['team_name_home', 'team_name_away', 
                  'goals_prediction']]

   team_name_home team_name_away  goals_prediction
0         Hungary    Switzerland               4.4
1           Spain        Croatia               2.9
2           Italy        Albania               1.6
3        Slovenia        Denmark               3.2
4          Serbia        England               4.2
5          Poland    Netherlands               2.9
6         Austria         France               3.0
7         Romania        Ukraine               2.5
8         Belgium       Slovakia               2.9
9        Türki̇ye        Georgia               3.2
10       Portugal        Czechia               4.5
11       Scotland    Switzerland               3.8
12        Croatia        Albania               1.7
13          Spain          Italy               2.6
14       Slovenia         Serbia               2.9
15        Denmark        England               4.2
16         Poland        Austria               3.8
17    Netherlands         France               3.0
18       Slovakia        Ukraine               2.3
19        Belgium        Romania               3.2
20        Georgia        Czechia               4.0
21       Türki̇ye       Portugal               3.4
22       Scotland        Hungary               2.9
23        Albania          Spain               3.3
24        Croatia          Italy               2.5
25        England       Slovenia               2.3
26        Denmark         Serbia               2.4
27    Netherlands        Austria               3.5
28         France         Poland               2.6
29       Slovakia        Romania               3.2
30        Ukraine        Belgium               3.2
31        Georgia       Portugal               3.1
32        Czechia       Türki̇ye               2.7

In [32]:
# check the slip
df_matches_stats[df_matches_stats.goals_prediction<=2.5][
    ['team_name_home', 'team_name_away', 'goals_prediction']]

   team_name_home team_name_away  goals_prediction
2           Italy        Albania               1.6
7         Romania        Ukraine               2.5
12        Croatia        Albania               1.7
18       Slovakia        Ukraine               2.3
24        Croatia          Italy               2.5
25        England       Slovenia               2.3
26        Denmark         Serbia               2.4

In [34]:
# check the slip
df_matches_stats[df_matches_stats.goals_prediction>3][
    ['team_name_home', 'team_name_away', 'goals_prediction']]

   team_name_home team_name_away  goals_prediction
0         Hungary    Switzerland               4.4
3        Slovenia        Denmark               3.2
4          Serbia        England               4.2
9        Türki̇ye        Georgia               3.2
10       Portugal        Czechia               4.5
11       Scotland    Switzerland               3.8
15        Denmark        England               4.2
16         Poland        Austria               3.8
19        Belgium        Romania               3.2
20        Georgia        Czechia               4.0
21       Türki̇ye       Portugal               3.4
23        Albania          Spain               3.3
27    Netherlands        Austria               3.5
29       Slovakia        Romania               3.2
30        Ukraine        Belgium               3.2
31        Georgia       Portugal               3.1